# Set PiHole password inside the container.
# sudo docker exec -it pihole pihole -a -p password

# Point PiHole Upstream DNS to use Unbound instead.
# cd unbound/
# sudo sed -i 's/interface: 0.0.0.0@53/interface: 0.0.0.0@5335/g' unbound.conf

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2024.07.0
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "8080:80/tcp"
    environment:
      TZ: 'Manila/Asia'
      PIHOLE_DNS_: unbound#5335
    volumes:
      - './pihole/:/etc/pihole/'
      - './dnsmasq/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5335:5335/tcp"
      - "5335:5335/udp"
    volumes:
      - './unbound/:/opt/unbound/etc/unbound/'
    restart: unless-stopped

