
# Custom export for xmonad-stack
export PATH="${PATH}:$HOME/.local/bin"

# My Personal Aliases
alias bt='rfkill block bluetooth && rfkill unblock bluetooth && bluetoothctl'
alias ll='ls -aAFhl --color=auto --time-style="+%b %d %I:%M %P"'
alias nv='nvim'
alias xx='xmonad --recompile; pkill xmobar; xmonad --restart'
alias cls='history -c && history -w'
alias vlc='vlc --fullscreen'
alias uml='sudo reflector --protocol https --sort rate --latest 5 --download-timeout 30 --save /etc/pacman.d/mirrorlist'
alias aa='setxkbmap us'
alias mm='setxkbmap -layout us -variant dvorak -option caps:escape'

salary () {
  python -c "print ('{:,.2f}'.format($1 * 4 * 40 * 50))"
}
export -f salary
