
# custom export for xmonad-stack install
export PATH="${PATH}:$HOME/.local/bin"

# custom aliases
alias bt='rfkill block bluetooth && rfkill unblock bluetooth && bluetoothctl'
alias ll='ls -aAFhl --color=auto --time-style="+%b %d %I:%M %P"'
alias nv='nvim'
alias xm='cd .cache/ && export GLOBIGNORE="xmonad" && rm -rf * && unset GLOBIGNORE'
alias xx='xmonad --recompile; pkill xmobar; xmonad --restart'
alias cls='history -c && history -w'

alias vlc='vlc --fullscreen'
alias uml='sudo reflector --protocol https --sort rate --latest 10 --download-timeout 15 --country "Hong Kong",Singapore --save /etc/pacman.d/mirrorlist'

alias aa='setxkbmap us'
alias mm='setxkbmap -layout us -variant dvorak -option caps:escape'

salary () {
  python -c "print ('{:,.2f}'.format($1 * 4 * 40 * 50))"
}
export -f salary
