services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - ./config:/config
      - ./cache:/cache
      - ./mnt/media/movies:/movies:ro
      - ./mnt/media/educational:/educational:ro
      - ./mnt/media/shows:/shows:ro
    restart: 'unless-stopped'
    group_add:
      - '105' # getent group render | cut -d: -f3
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    devices:
      - /dev/dri:/dev/dri

