services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: 'host'
    volumes:
      - /media/jellyfin/config:/config
      - /media/jellyfin/cache:/cache
      - type: bind
        source: /media/jellyfin/mnt/media/Movies
        target: /movies
      - type: bind
        source: /media/jellyfin/mnt/media/Shows
        target: /shows
        read_only: true
    restart: 'unless-stopped'
    environment:
      - JELLYFIN_PublishedServerUrl=http://example.com
    extra_hosts:
      - 'host.docker.internal:host-gateway'
